/*
 * Catalogue complémentaire Mwono.
 *
 * Format :
 * { fr: ["recherche française"], word: "forme locale", pronunciation: "...",
 *   category: "Thème", variant: "note pédagogique" }
 *
 * Ce fichier est volontairement séparé du moteur afin de pouvoir être enrichi,
 * relu par des locuteurs, puis remplacé plus tard par un vrai fichier JSON/API.
 */
window.MWONO_CATALOG = {
  shimaore: [
    { fr: ["refroidi", "c'est refroidi", "c est refroidi"], word: "Izilia", pronunciation: "i-zi-li-ya", category: "Cuisine", variant: "à table" },
    { fr: ["c'est trop salé", "c est trop sale", "trop salé", "trop sale"], word: "Ishia shingo", pronunciation: "i-shi-a chin-go", category: "Cuisine", variant: "à table" },
    { fr: ["il n'y a pas de sel", "il n y a pas de sel"], word: "Kaina shingo", pronunciation: "ka-i-na chin-go", category: "Cuisine", variant: "à table" },
    { fr: ["tremper dans du piment"], word: "Upatsa putu", pronunciation: "ou-pa-tsa pou-tou", category: "Cuisine", variant: "expression pratique" },
    { fr: ["ça a du goût", "ca a du gout"], word: "Ina ladha", pronunciation: "i-na la-dha", category: "Cuisine", variant: "à table" },
    { fr: ["c'est pimenté", "c est pimente"], word: "Ina putu", pronunciation: "i-na pou-tou", category: "Cuisine", variant: "à table" },
    { fr: ["lentement", "doucement"], word: "Pole pole", pronunciation: "po-lé po-lé", category: "Pratique", variant: "pour demander de ralentir" },
    { fr: ["aide-moi", "aide moi", "aidez-moi", "aidez moi"], word: "Nisaidie", pronunciation: "ni-sa-i-dié", category: "Pratique", variant: "demander de l'aide" },
    { fr: ["je ne sais pas", "je sais pas"], word: "Tsisijuwa", pronunciation: "tsi-ssi-jou-oi", category: "Pratique", variant: "utile quand on apprend" },
    { fr: ["je comprends", "j'ai compris", "j ai compris"], word: "Nisielewa", pronunciation: "ni-ssi-ou-é-lé-wa", category: "Pratique", variant: "utile quand on apprend" },
    { fr: ["je ne comprends pas", "je comprends pas"], word: "Tsisi uelewa", pronunciation: "tsi-ssi-ou-é-lé-wa", category: "Pratique", variant: "utile quand on apprend" },
    { fr: ["parler", "parlez"], word: "Ulagwa", pronunciation: "ou-lag-wa", category: "Actions", variant: "verbe" },
    { fr: ["écouter", "ecouter", "écoutez", "ecoutez"], word: "Uvulikia", pronunciation: "ou-vouli-kia", category: "Actions", variant: "verbe" },
    { fr: ["se réveiller", "se reveiller"], word: "Ulamuha", pronunciation: "ou-la-mou-ha", category: "Actions", variant: "verbe" },
    { fr: ["sursauter"], word: "Umaruha", pronunciation: "ou-ma-rou-ha", category: "Actions", variant: "verbe" },
    { fr: ["faire", "travailler"], word: "Ufanya hazi", pronunciation: "ou-fa-nia ha-zi", category: "Actions", variant: "verbe" },
    { fr: ["dire", "raconter"], word: "Urongwa", pronunciation: "ou-rong-wa", category: "Actions", variant: "verbe" },
    { fr: ["femme", "fille"], word: "Mtrumama", pronunciation: "m-trou-mama", category: "Famille", variant: "selon le contexte" },
    { fr: ["homme", "garçon", "garcon"], word: "Mtrumbaba", pronunciation: "m-trou-baba", category: "Famille", variant: "selon le contexte" },
    { fr: ["enfants", "les enfants"], word: "Wanatsa", pronunciation: "wa-na-tsa", category: "Famille", variant: "pluriel" },
    { fr: ["frère ou sœur", "frere ou soeur"], word: "Mwananya", pronunciation: "moi-na-gna", category: "Famille", variant: "terme générique" },
    { fr: ["mariage"], word: "Ndrola", pronunciation: "ndro-la", category: "Relations", variant: "famille" },
    { fr: ["voisins", "voisinage"], word: "Majirani", pronunciation: "ma-dji-ra-ni", category: "Relations", variant: "quotidien" },
    { fr: ["port"], word: "Bandari", pronunciation: "ban-da-ri", category: "Mayotte", variant: "lieu" },
    { fr: ["mer"], word: "Bahari", pronunciation: "ba-ha-ri", category: "Mayotte", variant: "nature" },
    { fr: ["village"], word: "Dago", pronunciation: "da-go", category: "Mayotte", variant: "lieu" },
    { fr: ["marché", "marche"], word: "Bazari", pronunciation: "ba-za-ri", category: "Quotidien", variant: "lieu" },
    { fr: ["école", "ecole"], word: "Likoli", pronunciation: "li-ko-li", category: "Quotidien", variant: "lieu" },
    { fr: ["hôpital", "hopital"], word: "Laptali", pronunciation: "la-pou-ta-li", category: "Quotidien", variant: "lieu" },
    { fr: ["mosquée", "mosquee"], word: "Mkiri", pronunciation: "m-ki-ri", category: "Quotidien", variant: "lieu" },
    { fr: ["véranda", "veranda", "terrasse"], word: "Bbaraza", pronunciation: "ba-ra-za", category: "Maison", variant: "lieu" },
    { fr: ["toit en terrasse"], word: "Bbanara", pronunciation: "ba-na-ra", category: "Maison", variant: "lieu" },
    { fr: ["étage"], word: "Dari", pronunciation: "da-ri", category: "Maison", variant: "lieu" },
    { fr: ["cuisine"], word: "Banga la upishia", pronunciation: "ban-ga-la-ou-pi-chia", category: "Maison", variant: "lieu" },
    { fr: ["riz", "riz non cuit"], word: "Tsohole", pronunciation: "mé-lé", category: "Cuisine", variant: "aliment" },
    { fr: ["huile"], word: "Matra", pronunciation: "ma-tra", category: "Cuisine", variant: "aliment" },
    { fr: ["marmite"], word: "Nyungu", pronunciation: "gnoun-gou", category: "Cuisine", variant: "ustensile" },
    { fr: ["couteau"], word: "Sembeya", pronunciation: "sin-be-ya", category: "Cuisine", variant: "ustensile" },
    { fr: ["avion"], word: "Ndege", pronunciation: "n-dè-gué", category: "Transport", variant: "déplacement" },
    { fr: ["route", "chemin"], word: "Pare", pronunciation: "pa-ré", category: "Transport", variant: "déplacement" },
    { fr: ["voyage", "trajet"], word: "Safari", pronunciation: "sa-fa-ri", category: "Transport", variant: "déplacement" },
    { fr: ["joie"], word: "Furaha", pronunciation: "fou-ra-ha", category: "Émotions", variant: "état" },
    { fr: ["amour"], word: "Mahaba", pronunciation: "ma-ha-ba", category: "Émotions", variant: "état" },
    { fr: ["espoir"], word: "Tumaini", pronunciation: "tou-ma-i-ni", category: "Émotions", variant: "état" },
    { fr: ["paix", "calme"], word: "Amani", pronunciation: "a-ma-ni", category: "Émotions", variant: "état" },
    { fr: ["fatigue"], word: "Ulemevu", pronunciation: "ou-lé-mouvu", category: "Émotions", variant: "état" },
    { fr: ["honte"], word: "Haya", pronunciation: "ha-ya", category: "Émotions", variant: "état" },
    { fr: ["à table", "manger"], word: "Udya", pronunciation: "ou-dya", category: "Actions", variant: "verbe" },
    { fr: ["boire"], word: "Unwa", pronunciation: "ou-noi", category: "Actions", variant: "verbe" },
    { fr: ["dormir"], word: "Ulala", pronunciation: "ou-la-la", category: "Actions", variant: "verbe" },
    { fr: ["aller"], word: "Uwendra", pronunciation: "ou-wen-dra", category: "Actions", variant: "verbe" },
    { fr: ["revenir"], word: "Urudi", pronunciation: "ou-rou-di", category: "Actions", variant: "verbe" },
    { fr: ["lire"], word: "Usoma", pronunciation: "ou-so-ma", category: "Actions", variant: "verbe" },
    { fr: ["écrire", "ecrire"], word: "Uhangiha", pronunciation: "ou-an-gui-ha", category: "Actions", variant: "verbe" },
    { fr: ["rire"], word: "Utseha", pronunciation: "ou-tsé-ha", category: "Actions", variant: "verbe" },
    { fr: ["pleurer"], word: "Ulia", pronunciation: "ou-li-a", category: "Actions", variant: "verbe" },
    { fr: ["jouer", "danser"], word: "Uãngadza", pronunciation: "ou-tché-za", category: "Actions", variant: "verbe" },
  ],
  breton: [
    { fr: ["bon", "bonne"], word: "Mat", pronunciation: "mat", category: "Adjectifs", variant: "qualité" },
    { fr: ["mauvais", "mauvaise"], word: "Fall", pronunciation: "fal", category: "Adjectifs", variant: "qualité" },
    { fr: ["grand", "grande"], word: "Bras", pronunciation: "bras", category: "Adjectifs", variant: "qualité" },
    { fr: ["petit", "petite"], word: "Bihan", pronunciation: "bi-an", category: "Adjectifs", variant: "qualité" },
    { fr: ["nouveau", "nouvelle"], word: "Nevez", pronunciation: "né-vé", category: "Adjectifs", variant: "qualité" },
    { fr: ["vieux", "vieille"], word: "Kozh", pronunciation: "koz", category: "Adjectifs", variant: "qualité" },
    { fr: ["facile"], word: "Aes", pronunciation: "ès", category: "Adjectifs", variant: "qualité" },
    { fr: ["difficile"], word: "Diaes", pronunciation: "di-ès", category: "Adjectifs", variant: "qualité" },
    { fr: ["aujourd'hui", "aujourd hui"], word: "Hiziv", pronunciation: "i-ziv", category: "Temps", variant: "repère" },
    { fr: ["demain"], word: "Warc'hoazh", pronunciation: "war-hoaz", category: "Temps", variant: "repère" },
    { fr: ["hier"], word: "Dec'h", pronunciation: "dèkh", category: "Temps", variant: "repère" },
    { fr: ["maintenant"], word: "Bremañ", pronunciation: "bré-man", category: "Temps", variant: "repère" },
    { fr: ["toujours"], word: "Bepred", pronunciation: "bé-préd", category: "Temps", variant: "repère" },
    { fr: ["jamais"], word: "Morse", pronunciation: "mor-sé", category: "Temps", variant: "repère" },
    { fr: ["être"], word: "Bezañ", pronunciation: "bé-zan", category: "Actions", variant: "verbe" },
    { fr: ["avoir"], word: "Kaout", pronunciation: "ka-out", category: "Actions", variant: "verbe" },
    { fr: ["faire"], word: "Ober", pronunciation: "o-ber", category: "Actions", variant: "verbe" },
    { fr: ["prendre"], word: "Kemer", pronunciation: "ké-mer", category: "Actions", variant: "verbe" },
    { fr: ["donner"], word: "Reiñ", pronunciation: "rein", category: "Actions", variant: "verbe" },
    { fr: ["demander"], word: "Goulenn", pronunciation: "gou-len", category: "Actions", variant: "verbe" },
    { fr: ["répondre", "repondre"], word: "Respont", pronunciation: "res-pont", category: "Actions", variant: "verbe" },
    { fr: ["penser"], word: "Soñjal", pronunciation: "son-yal", category: "Actions", variant: "verbe" },
    { fr: ["aimer"], word: "Karout", pronunciation: "ka-rout", category: "Actions", variant: "verbe" },
    { fr: ["connaître", "connaitre"], word: "Anavezout", pronunciation: "a-na-vé-out", category: "Actions", variant: "verbe" },
    { fr: ["attendre"], word: "Gortoz", pronunciation: "gor-toz", category: "Actions", variant: "verbe" },
    { fr: ["pêche", "peche"], word: "Pesketa", pronunciation: "pes-ké-ta", category: "Bretagne", variant: "activité" },
    { fr: ["bateau"], word: "Bag", pronunciation: "bag", category: "Bretagne", variant: "mer" },
    { fr: ["plage"], word: "Traezhenn", pronunciation: "tré-zen", category: "Bretagne", variant: "mer" },
    { fr: ["montagne"], word: "Menez", pronunciation: "mé-néz", category: "Nature", variant: "paysage" },
    { fr: ["chemin"], word: "Hent", pronunciation: "ent", category: "Lieux", variant: "déplacement" },
    { fr: ["forêt", "foret"], word: "Koad", pronunciation: "ko-at", category: "Nature", variant: "paysage" },
    { fr: ["campagne"], word: "Maez", pronunciation: "ma-éz", category: "Nature", variant: "paysage" },
    { fr: ["terre"], word: "Douar", pronunciation: "dou-ar", category: "Nature", variant: "paysage" },
    { fr: ["ciel"], word: "Neñv", pronunciation: "név", category: "Nature", variant: "paysage" },
    { fr: ["étoile", "etoile"], word: "Steredenn", pronunciation: "sté-ré-den", category: "Nature", variant: "ciel" },
    { fr: ["lune"], word: "Loar", pronunciation: "lo-ar", category: "Nature", variant: "ciel" },
    { fr: ["cheval"], word: "Marc'h", pronunciation: "mark", category: "Animaux", variant: "animal" },
    { fr: ["chien"], word: "Ki", pronunciation: "ki", category: "Animaux", variant: "animal" },
    { fr: ["chat"], word: "Kaz", pronunciation: "kaz", category: "Animaux", variant: "animal" },
    { fr: ["oiseau"], word: "Labous", pronunciation: "la-bous", category: "Animaux", variant: "animal" },
    { fr: ["arbre"], word: "Gwez", pronunciation: "gwéz", category: "Nature", variant: "végétal" },
    { fr: ["fleur"], word: "Bleunienn", pronunciation: "bleu-ni-en", category: "Nature", variant: "végétal" },
    { fr: ["pain"], word: "Bara", pronunciation: "ba-ra", category: "Cuisine", variant: "aliment" },
    { fr: ["beurre"], word: "Amann", pronunciation: "a-man", category: "Cuisine", variant: "aliment" },
    { fr: ["lait"], word: "Laezh", pronunciation: "lèz", category: "Cuisine", variant: "aliment" },
    { fr: ["pomme"], word: "Aval", pronunciation: "a-val", category: "Cuisine", variant: "aliment" },
    { fr: ["gâteau", "gateau"], word: "Kouign", pronunciation: "kou-in", category: "Cuisine", variant: "aliment" },
    { fr: ["café", "cafe"], word: "Kafe", pronunciation: "ka-fé", category: "Cuisine", variant: "boisson" },
    { fr: ["vin"], word: "Gwin", pronunciation: "gwin", category: "Cuisine", variant: "boisson" },
    { fr: ["rire"], word: "C'hoarzhin", pronunciation: "ho-ar-zin", category: "Actions", variant: "verbe" },
    { fr: ["jouer"], word: "C'hoari", pronunciation: "ho-a-ri", category: "Actions", variant: "verbe" },
    { fr: ["ouvrir"], word: "Digeriñ", pronunciation: "di-gé-rin", category: "Actions", variant: "verbe" },
    { fr: ["fermer"], word: "Serriñ", pronunciation: "sé-rin", category: "Actions", variant: "verbe" },
    { fr: ["chercher"], word: "Klask", pronunciation: "klask", category: "Actions", variant: "verbe" },
    { fr: ["trouver"], word: "Kavout", pronunciation: "ka-vout", category: "Actions", variant: "verbe" },
    { fr: ["perdre"], word: "Koll", pronunciation: "kol", category: "Actions", variant: "verbe" },
    { fr: ["commencer"], word: "Kregiñ", pronunciation: "kré-gin", category: "Actions", variant: "verbe" },
    { fr: ["finir"], word: "Echuiñ", pronunciation: "é-hwin", category: "Actions", variant: "verbe" },
    { fr: ["il pleut beaucoup", "beaucoup de pluie"], word: "Kalz a c'hlav zo", pronunciation: "kalz a glav zo", category: "Météo", variant: "phrase" },
    { fr: ["il fait froid aujourd'hui", "il fait froid aujourd hui"], word: "Yen eo an amzer hiziv", pronunciation: "yen éo an am-zér i-ziv", category: "Météo", variant: "phrase" },
    { fr: ["il fait beau aujourd'hui", "il fait beau aujourd hui"], word: "Brav eo an amzer hiziv", pronunciation: "brav éo an am-zér i-ziv", category: "Météo", variant: "phrase" },
    { fr: ["à bientôt"], word: "Ken ar wech all", pronunciation: "ken ar ouéch all", category: "Politesse", variant: "phrase" },
    { fr: ["bonne route"], word: "Hent mat", pronunciation: "ent mat", category: "Politesse", variant: "phrase" },
    { fr: ["bien joué", "bravo"], word: "Gourc'hemennoù", pronunciation: "gour-ké-men-no", category: "Politesse", variant: "encouragement" },
  ],
};
